### ISSUE TITLE
become a scout for a larger fund

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/hedgehog.vc#1]
hedgehog.vc needs money to fund investments

we don't want to invest from our own entity for legal/reporting reasons

instead, we plan on being a scout for an existing fund

we need to get more opinionated over cheque sizes and when we invest

todo:

- [ ] find a fund that would let us be a scout for it
- [ ] create clear view on what stage we invest at

**Comment by charlescook-ph** [comment]
updates on todos:

- awaiting feedback from 4 potential partners
- [pr created](https://github.com/PostHog/hedgehog.vc/pull/2) to clarify our investment parameters

**Comment by jamesefhawkins** [comment]
we now have agreement for up to $2m a year of investment, investing $100k each time.

* we make the decision ourselves
* we need to get pro rata each time (to justify the small cheque)
