### ISSUE TITLE
https://hedgehog.vc doesn't redirect

### ISSUE THREAD

**Issue by corywatilo** [PostHog/hedgehog.vc#8]
The redirect for the root domain with https doesn't redirect like it does if you type http

**Comment by charlescook-ph** [comment]
@fuziontech are you able to do this? (I think you registered the domain if I remember correctly...)

**Comment by fuziontech** [comment]
Done! I moved this from S3 redirect to the `redirector` box on EC2 because S3 redirection doesn't support TLS/HTTPS without cloudfront which is a bit heavy for a simple redirector
